{
 "title": "Flask App Overview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Request Rate (RPM)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "rate(flask_app_requests_total[5m])",
     "legendFormat": "{{path}} - status: {{http_status}} - method: {{method}}"
    }
   ]
  },
  {
   "title": "Request Latency - 95th Percentile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(flask_app_request_latency_seconds_bucket[5m])) by (le, endpoint))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Login Attempts",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(flask_app_login_attempts_total[1h])) by (status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(flask_app_active_requests)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Error Rate (%)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(flask_app_requests_total{http_status=~\"5.*\"}[5m])) / sum(rate(flask_app_requests_total[5m]))) * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}