---
- hosts: k8s_cluster
  become: yes
  roles:
    - common

- hosts: kube_control_plane
  become: yes
  roles:
    - control-plane

- hosts: kube_node
  become: yes
  roles:
    - join-cluster

- hosts: kube_control_plane
  become: no
  roles:
    - configure-cloud-integration

- hosts: localhost
  gather_facts: no
  roles:
    - prometheus-crds-and-ebs-csi