{
 "title": "Horizontal Pod Autoscaler Overview",
 "description": "A dashboard that monitors Kubernetes and focuses on giving a overview for horizontal pod autoscalers. It is based on the [kubernetes-autoscaling-mixin](https://github.com/adinhodovic/kubernetes-autoscaling-mixin).",
 "tags": [
  "kubernetes",
  "autoscaling",
  "kubernetes-autoscaling-mixin",
  "kubernetes-core"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(kube_horizontalpodautoscaler_metadata_generation{}, job)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_horizontalpodautoscaler_metadata_generation{job=~\"$job\"}, namespace)"
   },
   {
    "name": "hpa",
    "label": "Horitzontal Pod Autoscaler",
    "query": "label_values(kube_horizontalpodautoscaler_spec_target_metric{job=~\"$job\", namespace=\"$namespace\"},horizontalpodautoscaler)"
   },
   {
    "name": "metric_name",
    "label": "Metric Name",
    "query": "label_values(kube_horizontalpodautoscaler_spec_target_metric{job=~\"$job\", namespace=\"$namespace\", horizontalpodautoscaler=\"$hpa\"}, metric_name)"
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Desired Replicas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(\n  sum(\n    kube_horizontalpodautoscaler_status_desired_replicas{\n      job=~\"$job\",\n      namespace=~\"$namespace\",\n      horizontalpodautoscaler=\"$hpa\"\n    }\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Current Replicas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(\n  sum(\n    kube_horizontalpodautoscaler_status_current_replicas{\n      job=~\"$job\",\n      namespace=~\"$namespace\",\n      horizontalpodautoscaler=\"$hpa\"\n    }\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Min Replicas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(\n  sum(\n    kube_horizontalpodautoscaler_spec_min_replicas{\n      job=~\"$job\",\n      namespace=~\"$namespace\",\n      horizontalpodautoscaler=\"$hpa\"\n    }\n  )\n)\n"
    }
   ]
  },
  {
   "title": "Max Replicas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(\n  sum(\n    kube_horizontalpodautoscaler_spec_max_replicas{\n      job=~\"$job\",\n      namespace=~\"$namespace\",\n      horizontalpodautoscaler=\"$hpa\"\n    }\n  )\n)\n"
    }
   ]
  },
  {
   "title": "CPU Utilization (% of Pod Limit)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", container!=\"\"}[1m])) / sum by (pod) (kube_pod_container_resource_limits{namespace=~\"$namespace\", resource=\"cpu\", container!=\"\"})",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Replica time to state running",
   "type": "table",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "max(\r\n  kube_pod_status_ready_time{namespace=\"application\"} \r\n  - kube_pod_created{namespace=\"application\"}\r\n) by (pod)\r\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Metric Targets",
   "type": "table",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(\n  sum(\n    kube_horizontalpodautoscaler_spec_target_metric{\n      job=~\"$job\",\n      namespace=~\"$namespace\",\n      horizontalpodautoscaler=\"$hpa\",\n      metric_name=~\"$metric_name\"\n    }\n  ) by (job, namespace, horizontalpodautoscaler, metric_name, metric_target_type)\n)\n"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(\n  sum(\n    kube_horizontalpodautoscaler_status_desired_replicas{\n      job=~\"$job\",\n      namespace=~\"$namespace\",\n      horizontalpodautoscaler=\"$hpa\"\n    }\n  )\n)\n",
     "legendFormat": "Desired Replicas"
    },
    {
     "expr": "round(\n  sum(\n    kube_horizontalpodautoscaler_status_current_replicas{\n      job=~\"$job\",\n      namespace=~\"$namespace\",\n      horizontalpodautoscaler=\"$hpa\"\n    }\n  )\n)\n",
     "legendFormat": "Current Replicas"
    },
    {
     "expr": "round(\n  sum(\n    kube_horizontalpodautoscaler_spec_min_replicas{\n      job=~\"$job\",\n      namespace=~\"$namespace\",\n      horizontalpodautoscaler=\"$hpa\"\n    }\n  )\n)\n",
     "legendFormat": "Min Replicas"
    },
    {
     "expr": "round(\n  sum(\n    kube_horizontalpodautoscaler_spec_max_replicas{\n      job=~\"$job\",\n      namespace=~\"$namespace\",\n      horizontalpodautoscaler=\"$hpa\"\n    }\n  )\n)\n",
     "legendFormat": "Max Replicas"
    }
   ]
  }
 ]
}