loki:
  persistence:
    enabled: true
    storageClassName: gp2
    size: 1Gi

# Promtail configuration
promtail:
  replicas: 1
  enabled: true
  config:
    scrape_configs: |
      - job_name: kubernetes-pods
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            target_label: app
          - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
            target_label: app
          - source_labels: [__meta_kubernetes_namespace]
            target_label: namespace
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod
        pipeline_stages:
          - match:
              selector: '{app="flask-app"}'
              stages:
                - multiline:
                    firstline: '^time='
                    max_wait_time: 3s
                - logfmt: {}
                - labels:
                    level:
                    method:
                    status_code:
          - docker: {}

# We disable Grafana in this stack because we use the one from kube-prometheus-stack.
grafana:
  enabled: false