alertmanager:
  enabled: false

# Prometheus Configuration
prometheus:
  prometheusSpec:
    replicas: 1
    retention: 10d
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: gp2
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi

# Grafana Configuration
grafana:
  enabled: true
  replicas: 1

  # Configuration of additional data sources (Loki).
  additionalDataSources:
    - name: Loki
      type: loki
      url: http://loki-stack.monitoring.svc.cluster.local:3100
      access: proxy
      isDefault: false

  # Configuration of automatic dashboard provisioning.
  dashboardProviders:
    dashboard-provider.yaml:
      apiVersion: 1
      providers:
        - name: 'default'
          orgId: 1
          folder: 'My-App'
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/default

  # Definition of dashboards to be loaded.
  dashboards:
    default:
      # Name of the key in ConfigMap.
      flask-app-overview:
        # Pointing to the JSON file with the dashboard definition.
        json: ""