name: Build & Push Docker Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Test
        run: echo "This is a test step to ensure the workflow runs correctly."