name: Helmfile Lint

on:
  workflow_call:
    inputs:
      helmfile_path:
        description: 'The path to the Helmfile to lint'
        required: false
        type: string
        default: 'helmfile/aws-selfhosted/helmfile.gotmpl'

jobs:
  lint-chart:
    name: Lint Helmfile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Helmfile
        uses: memezou-tech/setup-helmfile@v2.1.0

      - name: Run Helmfile Lint
        run: helmfile lint -f ${{ inputs.helmfile_path }}