name: Helmfile Lint

on:
  workflow_call:
    inputs:
      workdir:
        description: 'Working directory for helmfile'
        required: false
        type: string
        default: 'helmfile/aws/'
      environment:
        description: 'The environment to lint the Helmfile against'
        required: true
        type: string
        
jobs:
  lint-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Helmfile Lint
        uses: helmfile/helmfile-action@v2.0.5
        with:
          helmfile-args: -e ${{ inputs.environment }} -f ${{ inputs.workdir }}/helmfile.yaml.gotmpl lint